### ISSUE TITLE
Commit a Cargo.lock

### ISSUE THREAD

**Issue by zyklotomic** [arighi/virtme-ng-init#8]
Could you consider committing a `Cargo.lock` into the repo? See https://doc.rust-lang.org/cargo/faq.html#why-have-cargolock-in-version-control. From that link, I think it can be a subjective choice. Committing `Cargo.lock` would benefit build reproducibility and would have how _you_ built `virtme-ng-init` as the source of truth.

For example, when writing a Nix flake for building virtme-ng, I had to manually add my own:
https://github.com/zyklotomic/virtme-ng-flake.nix/blob/293989be1d8a5234eae2049912acc2643141ab2b/flake.nix#L26
https://github.com/zyklotomic/virtme-ng-flake.nix/blob/293989be1d8a5234eae2049912acc2643141ab2b/Cargo.lock

It would also save me from having to update the `Cargo.lock` myself and risk using inconsistent dependencies.

Thank you so much Andrea, I really appreciate your work on this by the way!

**Comment by arighi** [comment]
Sounds like a reasonable idea to me. I'll add a Cargo.lock.

Thanks for the suggestion!

**Comment by zyklotomic** [comment]
Thanks for adding it!
